workflows:
  ios-app:
    name: iOS App Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          cd ios
          pod install --verbose
          cd ..
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/ios/archive/App.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath build/ios/archive/App.xcarchive \
                     -exportPath build/ios/iphoneos \
                     -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - "your-email@example.com"
